server {
    listen 8080;
    server_name localhost;
    host 127.0.0.1;
    root test_autoindex;
    index index.html;

    location / {
        allow_methods GET HEAD POST;
        autoindex on;
        upload_store www/uploads;
        cgi_pass .py /usr/bin/python3;
    }
}
